# Generated by Django 4.1 on 2022-08-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consejos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
